SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `feneko_manyforms_01` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `t31` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `t32` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `t33` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `t34` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `t35` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `t36` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `t37` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `t38` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `t39` varchar(100) NOT NULL,
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `profiel` varchar(100) NOT NULL COMMENT 'profiel',
  `bevestiging` varchar(100) NOT NULL COMMENT 'bevestiging',
  `soort_bevestiging` varchar(100) DEFAULT NULL COMMENT 'soort_bevestiging',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `opties` varchar(100) DEFAULT 'nvt' COMMENT 'opties',
  `file` int(10) unsigned DEFAULT '0' COMMENT 'fid of related file',
  `borstel_profiel` varchar(16) DEFAULT 'nvt' COMMENT 'borstel profiel',
  `borstel` varchar(16) DEFAULT 'nvt' COMMENT 'borstel'
) ENGINE=InnoDB AUTO_INCREMENT=7886 DEFAULT CHARSET=utf8 COMMENT='Form 01';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_02` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `t31` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `t32` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `t33` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `t34` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `t35` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `t36` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `t37` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `t38` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `t39` varchar(100) NOT NULL,
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `bevestiging` varchar(100) NOT NULL COMMENT 'bevestiging',
  `soort_bevestiging` varchar(100) DEFAULT NULL COMMENT 'soort_bevestiging',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `pvc` varchar(100) NOT NULL DEFAULT 'nvt' COMMENT 'kleuren toebehoren pvc',
  `borstel_profiel` varchar(16) DEFAULT 'nvt' COMMENT 'borstel profiel',
  `borstel` varchar(16) DEFAULT 'nvt' COMMENT 'borstel'
) ENGINE=InnoDB AUTO_INCREMENT=965 DEFAULT CHARSET=utf8 COMMENT='Form 02';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_03` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `t31` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `t32` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `t33` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `t34` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `t35` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `t36` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `t37` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `t38` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `t39` varchar(100) NOT NULL,
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `profiel` varchar(100) NOT NULL COMMENT 'profiel',
  `diepte` varchar(100) DEFAULT NULL COMMENT 'diepte',
  `soort_bevestiging` varchar(100) DEFAULT NULL COMMENT 'soort_bevestiging',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `pvc` varchar(100) NOT NULL DEFAULT 'nvt' COMMENT 'kleuren toebehoren pvc',
  `speling` varchar(16) DEFAULT NULL COMMENT 'speling voorzien'
) ENGINE=InnoDB AUTO_INCREMENT=137 DEFAULT CHARSET=utf8 COMMENT='Form 03';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_04` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `t31` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `t32` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `t33` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `t34` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `t35` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `t36` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `t37` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `t38` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `t39` varchar(100) NOT NULL,
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `scharnierkant` varchar(100) DEFAULT NULL,
  `pomp` varchar(100) DEFAULT NULL,
  `plint` varchar(100) NOT NULL COMMENT 'plint',
  `dierendeur` varchar(100) DEFAULT NULL COMMENT 'dierendeur',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `pvc` varchar(100) NOT NULL DEFAULT 'nvt' COMMENT 'kleuren toebehoren pvc'
) ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8 COMMENT='Form 04';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_05` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `t31` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `t32` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `t33` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `t34` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `t35` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `t36` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `t37` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `t38` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `t39` varchar(100) NOT NULL,
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `uitvoering` varchar(100) NOT NULL COMMENT 'uitvoering',
  `kader` varchar(100) DEFAULT NULL COMMENT 'kader',
  `scharnierkant` varchar(100) DEFAULT NULL,
  `pomp` varchar(100) DEFAULT NULL,
  `plint` varchar(100) NOT NULL COMMENT 'plint',
  `dierendeur` varchar(100) DEFAULT NULL COMMENT 'dierendeur',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `opties` varchar(100) DEFAULT 'nvt' COMMENT 'opties',
  `file` int(10) unsigned DEFAULT '0' COMMENT 'fid of related file',
  `pvc` varchar(100) NOT NULL DEFAULT 'nvt' COMMENT 'kleuren toebehoren pvc',
  `afdekdoppen` varchar(16) DEFAULT NULL COMMENT 'afdekdoppen'
) ENGINE=InnoDB AUTO_INCREMENT=1023 DEFAULT CHARSET=utf8 COMMENT='Form 05';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_06` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `t31` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `t32` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `t33` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `t34` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `t35` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `t36` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `t37` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `t38` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `t39` varchar(100) NOT NULL,
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `uitvoering` varchar(100) NOT NULL COMMENT 'uitvoering',
  `kader` varchar(100) DEFAULT NULL COMMENT 'kader',
  `scharnierkant` varchar(100) DEFAULT NULL,
  `pomp` varchar(100) DEFAULT NULL,
  `plint` varchar(100) NOT NULL COMMENT 'plint',
  `dierendeur` varchar(100) DEFAULT NULL COMMENT 'dierendeur',
  `hoekverbinding` varchar(100) DEFAULT NULL COMMENT 'hoekverbinding',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `opties` varchar(100) DEFAULT 'nvt' COMMENT 'opties'
) ENGINE=InnoDB AUTO_INCREMENT=1067 DEFAULT CHARSET=utf8 COMMENT='Form 06';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_07` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `rails1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `rails2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `rails3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `rails4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `rails5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `rails6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `rails7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `rails8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `rails9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `ondergeleider` varchar(100) NOT NULL COMMENT 'ondergeleider',
  `bovengeleider` varchar(100) NOT NULL COMMENT 'bovengeleider',
  `plint` varchar(100) NOT NULL COMMENT 'plint',
  `dierendeur` varchar(100) DEFAULT NULL COMMENT 'dierendeur',
  `borstel_links` varchar(100) NOT NULL COMMENT 'borstel_links',
  `borstel_rechts` varchar(100) NOT NULL COMMENT 'borstel_rechts',
  `eindstoppen` varchar(100) NOT NULL COMMENT 'eindstoppen',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `pvc` varchar(100) NOT NULL DEFAULT 'nvt' COMMENT 'kleuren toebehoren pvc'
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8 COMMENT='Form 07';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_08` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `rails1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `rails2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `rails3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `rails4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `rails5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `rails6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `rails7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `rails8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `rails9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `uitvoering` varchar(100) NOT NULL COMMENT 'uitvoering',
  `ondergeleider` varchar(100) NOT NULL COMMENT 'ondergeleider',
  `bovengeleider` varchar(100) NOT NULL COMMENT 'bovengeleider',
  `plint` varchar(100) NOT NULL COMMENT 'plint',
  `dierendeur` varchar(100) DEFAULT NULL COMMENT 'dierendeur',
  `borstel_links` varchar(100) NOT NULL COMMENT 'borstel_links',
  `borstel_rechts` varchar(100) NOT NULL COMMENT 'borstel_rechts',
  `eindstoppen` varchar(100) NOT NULL COMMENT 'eindstoppen',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL,
  `pvc` varchar(100) NOT NULL DEFAULT 'nvt' COMMENT 'kleuren toebehoren pvc'
) ENGINE=InnoDB AUTO_INCREMENT=1341 DEFAULT CHARSET=utf8 COMMENT='Form 08';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_09` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `rails1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `rails2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `rails3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `rails4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `rails5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `rails6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `rails7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `rails8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `rails9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `uitvoering` varchar(100) NOT NULL COMMENT 'uitvoering',
  `ondergeleider` varchar(100) NOT NULL COMMENT 'ondergeleider',
  `bovengeleider` varchar(100) NOT NULL COMMENT 'bovengeleider',
  `borstel_kopse_kant` varchar(100) NOT NULL COMMENT 'borstel_kopse_kant',
  `plint` varchar(100) NOT NULL COMMENT 'plint',
  `dierendeur` varchar(100) DEFAULT NULL COMMENT 'dierendeur',
  `borstel_links` varchar(100) NOT NULL COMMENT 'borstel_links',
  `borstel_rechts` varchar(100) NOT NULL COMMENT 'borstel_rechts',
  `eindstoppen` varchar(100) NOT NULL COMMENT 'eindstoppen',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1786 DEFAULT CHARSET=utf8 COMMENT='Form 09';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_10` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `rails1` bigint(20) DEFAULT NULL,
  `stand1` bigint(20) DEFAULT NULL,
  `t11` varchar(100) NOT NULL,
  `t21` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `rails2` bigint(20) DEFAULT NULL,
  `stand2` bigint(20) DEFAULT NULL,
  `t12` varchar(100) NOT NULL,
  `t22` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `rails3` bigint(20) DEFAULT NULL,
  `stand3` bigint(20) DEFAULT NULL,
  `t13` varchar(100) NOT NULL,
  `t23` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `rails4` bigint(20) DEFAULT NULL,
  `stand4` bigint(20) DEFAULT NULL,
  `t14` varchar(100) NOT NULL,
  `t24` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `rails5` bigint(20) DEFAULT NULL,
  `stand5` bigint(20) DEFAULT NULL,
  `t15` varchar(100) NOT NULL,
  `t25` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `rails6` bigint(20) DEFAULT NULL,
  `stand6` bigint(20) DEFAULT NULL,
  `t16` varchar(100) NOT NULL,
  `t26` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `rails7` bigint(20) DEFAULT NULL,
  `stand7` bigint(20) DEFAULT NULL,
  `t17` varchar(100) NOT NULL,
  `t27` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `rails8` bigint(20) DEFAULT NULL,
  `stand8` bigint(20) DEFAULT NULL,
  `t18` varchar(100) NOT NULL,
  `t28` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `rails9` bigint(20) DEFAULT NULL,
  `stand9` bigint(20) DEFAULT NULL,
  `t19` varchar(100) NOT NULL,
  `t29` varchar(100) NOT NULL,
  `uitvoering` varchar(100) NOT NULL COMMENT 'uitvoering',
  `ondergeleider` varchar(100) NOT NULL COMMENT 'ondergeleider',
  `bovengeleider` varchar(100) NOT NULL COMMENT 'bovengeleider',
  `stootrubber` varchar(100) NOT NULL COMMENT 'stootrubber',
  `plint` varchar(100) NOT NULL COMMENT 'plint',
  `dierendeur` varchar(100) DEFAULT NULL COMMENT 'dierendeur',
  `borstel_links` varchar(100) NOT NULL COMMENT 'borstel_links',
  `borstel_rechts` varchar(100) NOT NULL COMMENT 'borstel_rechts',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=566 DEFAULT CHARSET=utf8 COMMENT='Form 10';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_11` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `rails1` bigint(20) DEFAULT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `rails2` bigint(20) DEFAULT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `rails3` bigint(20) DEFAULT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `rails4` bigint(20) DEFAULT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `rails5` bigint(20) DEFAULT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `rails6` bigint(20) DEFAULT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `rails7` bigint(20) DEFAULT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `rails8` bigint(20) DEFAULT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `rails9` bigint(20) DEFAULT NULL,
  `uitvoering` varchar(100) NOT NULL COMMENT 'uitvoering',
  `ondergeleider` varchar(100) NOT NULL COMMENT 'ondergeleider',
  `verbreding` varchar(100) NOT NULL COMMENT 'verbreding',
  `kader_top` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Top checkbox of kader',
  `kader_left` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Left checkbox of kader',
  `kader_right` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Right checkbox of kader',
  `kader_bottom` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Bottom checkbox of kader',
  `borstel` varchar(100) NOT NULL COMMENT 'borstel',
  `diepte_borstel` varchar(100) DEFAULT NULL COMMENT 'diepte_borstel',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1082 DEFAULT CHARSET=utf8 COMMENT='Form 11';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_12` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `kader` varchar(100) DEFAULT NULL COMMENT 'kader',
  `opmerking1` varchar(100) DEFAULT NULL,
  `opmerking2` varchar(100) DEFAULT NULL,
  `opmerking3` varchar(100) DEFAULT NULL,
  `opmerking4` varchar(100) DEFAULT NULL,
  `opmerking5` varchar(100) DEFAULT NULL,
  `opmerking6` varchar(100) DEFAULT NULL,
  `opmerking7` varchar(100) DEFAULT NULL,
  `opmerking8` varchar(100) DEFAULT NULL,
  `opmerking9` varchar(100) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=231 DEFAULT CHARSET=utf8 COMMENT='Form 12';

CREATE TABLE IF NOT EXISTS `feneko_manyforms_13` (
`id` int(10) unsigned NOT NULL COMMENT 'The primary identifier',
  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'user identifier',
  `datesubmit` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'submission date',
  `exported` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Flag to store if the item has been exported before',
  `klant` varchar(100) NOT NULL COMMENT 'klant',
  `referentie` varchar(100) NOT NULL COMMENT 'referentie',
  `kleur` varchar(100) NOT NULL COMMENT 'kleur',
  `type_gaas` varchar(100) NOT NULL COMMENT 'type_gaas',
  `gaas_kleur` varchar(100) DEFAULT NULL COMMENT 'gaas_kleur',
  `kleur_pees` varchar(100) NOT NULL COMMENT 'kleur_pees',
  `kies_een_optie` varchar(100) NOT NULL COMMENT 'kies_een_optie',
  `aantal1` bigint(20) DEFAULT NULL,
  `breedte1` bigint(20) DEFAULT NULL,
  `hoogte1` bigint(20) DEFAULT NULL,
  `rails1` bigint(20) DEFAULT NULL,
  `opmerking1` varchar(100) NOT NULL,
  `aantal2` bigint(20) DEFAULT NULL,
  `breedte2` bigint(20) DEFAULT NULL,
  `hoogte2` bigint(20) DEFAULT NULL,
  `rails2` bigint(20) DEFAULT NULL,
  `opmerking2` varchar(100) NOT NULL,
  `aantal3` bigint(20) DEFAULT NULL,
  `breedte3` bigint(20) DEFAULT NULL,
  `hoogte3` bigint(20) DEFAULT NULL,
  `rails3` bigint(20) DEFAULT NULL,
  `opmerking3` varchar(100) NOT NULL,
  `aantal4` bigint(20) DEFAULT NULL,
  `breedte4` bigint(20) DEFAULT NULL,
  `hoogte4` bigint(20) DEFAULT NULL,
  `rails4` bigint(20) DEFAULT NULL,
  `opmerking4` varchar(100) NOT NULL,
  `aantal5` bigint(20) DEFAULT NULL,
  `breedte5` bigint(20) DEFAULT NULL,
  `hoogte5` bigint(20) DEFAULT NULL,
  `rails5` bigint(20) DEFAULT NULL,
  `opmerking5` varchar(100) NOT NULL,
  `aantal6` bigint(20) DEFAULT NULL,
  `breedte6` bigint(20) DEFAULT NULL,
  `hoogte6` bigint(20) DEFAULT NULL,
  `rails6` bigint(20) DEFAULT NULL,
  `opmerking6` varchar(100) NOT NULL,
  `aantal7` bigint(20) DEFAULT NULL,
  `breedte7` bigint(20) DEFAULT NULL,
  `hoogte7` bigint(20) DEFAULT NULL,
  `rails7` bigint(20) DEFAULT NULL,
  `opmerking7` varchar(100) NOT NULL,
  `aantal8` bigint(20) DEFAULT NULL,
  `breedte8` bigint(20) DEFAULT NULL,
  `hoogte8` bigint(20) DEFAULT NULL,
  `rails8` bigint(20) DEFAULT NULL,
  `opmerking8` varchar(100) NOT NULL,
  `aantal9` bigint(20) DEFAULT NULL,
  `breedte9` bigint(20) DEFAULT NULL,
  `hoogte9` bigint(20) DEFAULT NULL,
  `rails9` bigint(20) DEFAULT NULL,
  `opmerking9` varchar(100) NOT NULL,
  `ondergeleider` varchar(100) NOT NULL COMMENT 'ondergeleider',
  `ondergeleider_anodise` varchar(100) NOT NULL COMMENT 'ondergeleider_anodise',
  `bovengeleider` varchar(100) NOT NULL COMMENT 'bovengeleider',
  `borstel_kopse_kant` varchar(100) NOT NULL COMMENT 'borstel_kopse_kant',
  `borstel_links` varchar(100) NOT NULL COMMENT 'borstel_links',
  `borstel_rechts` varchar(100) NOT NULL COMMENT 'borstel_rechts',
  `eindstoppen` varchar(100) NOT NULL COMMENT 'eindstoppen'
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT='Form 13';


ALTER TABLE `feneko_manyforms_01`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_02`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_03`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_04`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_05`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_06`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_07`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_08`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_09`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_10`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_11`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_12`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `feneko_manyforms_13`
 ADD PRIMARY KEY (`id`);


ALTER TABLE `feneko_manyforms_01`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=7886;
ALTER TABLE `feneko_manyforms_02`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=965;
ALTER TABLE `feneko_manyforms_03`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=137;
ALTER TABLE `feneko_manyforms_04`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=69;
ALTER TABLE `feneko_manyforms_05`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=1023;
ALTER TABLE `feneko_manyforms_06`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=1067;
ALTER TABLE `feneko_manyforms_07`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=64;
ALTER TABLE `feneko_manyforms_08`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=1341;
ALTER TABLE `feneko_manyforms_09`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=1786;
ALTER TABLE `feneko_manyforms_10`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=566;
ALTER TABLE `feneko_manyforms_11`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=1082;
ALTER TABLE `feneko_manyforms_12`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=231;
ALTER TABLE `feneko_manyforms_13`
MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary identifier',AUTO_INCREMENT=10;
