<?php
/**
 * @file
 * feneko_account.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function feneko_account_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "services" && $api == "services") {
    return array("version" => "3");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
