<?php
/**
 * @file
 * Code for the Feneko Account feature.
 */

include_once 'feneko_account.features.inc';

/**
 * Implements hook_node_access
 */
function feneko_account_node_access($node, $op, $account) {
  if(is_object($node)) {
    switch ($node->type) {
      // Block access to client nodes for non authorized users
      case 'client':
        // A user has only view access to his own clients
        $clientIds = array_keys(feneko_code_get_clients_options(true));
        if(in_array($node->nid, $clientIds) && $op === 'view') {
          return NODE_ACCESS_ALLOW;
        }

        // A site admin has access to all clients
        $role_id = array_search('site_admin', user_roles());
        if(user_has_role($role_id, $account)) {
          return NODE_ACCESS_ALLOW;
        }

        return NODE_ACCESS_DENY;

      // Block access to the view page of a banner
      case 'banner':
        // A content editor has full access to all banners
        $role_id = array_search('content editor', user_roles());
        if(user_has_role($role_id, $account)) {
          return NODE_ACCESS_ALLOW;
        }

        return NODE_ACCESS_DENY;
    }
  }
}
