<?php
/**
 * Implements hook_libraries_info().
 */

function feneko_libraries_libraries_info() {
  $libraries['mpdf'] = array(
    'name' => 'mPDF',
    'vendor url' => 'http://www.mpdf1.com',
    'download url' => 'http://www.mpdf1.com/mpdf/index.php?page=Download',
    'version arguments' => array(
      'file' => 'CHANGELOG.txt', // Could be any file with version info
      'pattern' => '/mPDF (.+)/',
      'lines' => 2,
    ),
    'files' => array(
      'php' => array('mpdf.php'),
    ),
  );

  $libraries['zipstream'] = array(
    'name' => 'zipstream',
    'vendor url' => 'http://pablotron.org/software/zipstream-php/',
    'download url' => 'http://pablotron.org/files/zipstream-php-0.2.2.tar.gz',
    'version arguments' => array(
      'file' => 'README', // Could be any file with version info
      'pattern' => '/ZipStream (.+) README/',
      'lines' => 1,
    ),
    'files' => array(
      'php' => array('zipstream.php'),
    ),
  );

  return $libraries;
}
