<?php
/**
 * @file
 * feneko_translations.features.translations_fr.inc
 */

/**
 * Implements hook_translations_fr_defaults().
 */
function feneko_translations_translations_fr_defaults() {
  $translations = array();
  $translatables = array();
  $translations['fr:default']['1be4d5724335ae5b04677832fd631e9a'] = array(
    'source' => 'Solliciteren tot (alle talen)',
    'context' => '',
    'location' => '/nl/node/205/edit/nl',
    'translation' => 'Solliciter jusqu\'au',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Solliciteren tot (alle talen)', array(), array('context' => ''));
  $translations['fr:default']['1de4d5dfa38d97e77ebb3401582c49c6'] = array(
    'source' => 'Solliciteren tot',
    'context' => '',
    'location' => '/node/28/edit',
    'translation' => 'Solliciter jusqu\'au',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Solliciteren tot', array(), array('context' => ''));
  $translations['fr:default']['2da091108abf54b72117e0b07776002c'] = array(
    'source' => 'Onze producten',
    'context' => '',
    'location' => '/admin/structure/views/add',
    'translation' => 'Nos produits',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Onze producten', array(), array('context' => ''));
  $translations['fr:default']['45acd6ac4b264cef2bccfdc5a5e048d1'] = array(
    'source' => 'Klant worden',
    'context' => '',
    'location' => '/nl/admin/structure/views/view/about/edit/page_2',
    'translation' => 'Devenir client',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Klant worden', array(), array('context' => ''));
  $translations['fr:default']['4da26939619ccf77cae38bebef10e168'] = array(
    'source' => 'Al onze leveringen gebeuren tussen de 8 en 12 werkdagen.',
    'context' => '',
    'location' => '/fr/fa%C3%A7onnage/fa%C3%A7onnage',
    'translation' => 'Toutes nos livraisons se produisent entre 8 et 12 jours de travail.',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Al onze leveringen gebeuren tussen de 8 en 12 werkdagen.', array(), array('context' => ''));
  $translations['fr:default']['648930cf62ba900667f41bd903a76a21'] = array(
    'source' => 'Solliciteren tot (toutes les langues)',
    'context' => '',
    'location' => '/fr/node/205/edit/add/nl/fr',
    'translation' => 'Solliciter jusqu\'au',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Solliciteren tot (toutes les langues)', array(), array('context' => ''));
  $translations['fr:default']['68125a15512031e938b712b5e3578034'] = array(
    'source' => 'Wij zoeken',
    'context' => '',
    'location' => '/nl/admin/structure/features',
    'translation' => 'Nous cherchons',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Wij zoeken', array(), array('context' => ''));
  $translations['fr:default']['72eacb1fb5db6c9ae0f752fae1f3c7a1'] = array(
    'source' => 'Wij bieden',
    'context' => '',
    'location' => '/nl/admin/structure/features',
    'translation' => 'Nous offrons',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Wij bieden', array(), array('context' => ''));
  $translations['fr:default']['88312199623a59a893fa2c0f5fb4a4af'] = array(
    'source' => 'Andere jobs',
    'context' => '',
    'location' => '/fr/jobs/test-vacature-fr-0',
    'translation' => 'Autres jobs',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Andere jobs', array(), array('context' => ''));
  $translations['fr:default']['dd8ace8df7e819fa3a8be48135c50107'] = array(
    'source' => 'Levertijden',
    'context' => '',
    'location' => '/nl/admin/structure/views/view/about/edit/page',
    'translation' => 'Délai de livraison',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Levertijden', array(), array('context' => ''));
  $translations['fr:default']['e3d998fafda50c0ed95985bc13632bd0'] = array(
    'source' => 'Nieuws',
    'context' => '',
    'location' => '/admin/structure/views/view/nieuws/edit/page',
    'translation' => 'Nouvelles',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Nieuws', array(), array('context' => ''));
  $translations['fr:default']['ea22a9e38ce6daabf42557163ec3f009'] = array(
    'source' => 'Naam',
    'context' => '',
    'location' => '/admin/structure/types/add',
    'translation' => 'Nom',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Naam', array(), array('context' => ''));
  $translations['fr:field']['1c54a6a124fad27d45e37ae53801218a'] = array(
    'source' => 'Naam',
    'context' => 'field_naam:contact:label',
    'location' => 'field:field_naam:contact:label',
    'translation' => 'Nom',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Naam', array(), array('context' => 'field_naam:contact:label'));
  $translations['fr:field']['22f5160682267b7851449c43593a07b7'] = array(
    'source' => 'Wij bieden',
    'context' => 'field_offering:vacature:label',
    'location' => 'field:field_offering:vacature:label',
    'translation' => 'Nous offrons',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Wij bieden', array(), array('context' => 'field_offering:vacature:label'));
  $translations['fr:field']['2edbc23e387b743c32b68e7a81d83319'] = array(
    'source' => 'Uw vraag',
    'context' => 'field_uw_vraag:contact:label',
    'location' => 'field:field_uw_vraag:contact:label',
    'translation' => 'Votre question',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Uw vraag', array(), array('context' => 'field_uw_vraag:contact:label'));
  $translations['fr:field']['6d1dbe4b85ebf9588816fdd06fa2eb84'] = array(
    'source' => 'Wij zoeken',
    'context' => 'field_wanted:vacature:label',
    'location' => 'field:field_wanted:vacature:label',
    'translation' => 'Nous cherchons',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Wij zoeken', array(), array('context' => 'field_wanted:vacature:label'));
  $translations['fr:field']['7f81cd380c0deb5e984398a3bf646fcc'] = array(
    'source' => 'Solliciteren tot',
    'context' => 'field_ultimate_date:vacature:label',
    'location' => 'field:field_ultimate_date:vacature:label',
    'translation' => 'Solliciter jusqu\'au',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Solliciteren tot', array(), array('context' => 'field_ultimate_date:vacature:label'));
  $translations['fr:field']['81730bea484e5b05f2ccd84c3d97ed5f'] = array(
    'source' => 'Naam',
    'context' => 'field_naam:solliciteer:label',
    'location' => 'field:field_naam:solliciteer:label',
    'translation' => 'Nom',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Naam', array(), array('context' => 'field_naam:solliciteer:label'));
  $translations['fr:node']['fb7dd62d2d4e3577bcd83d120a54581b'] = array(
    'source' => 'Naam',
    'context' => 'type:product:title_label',
    'location' => 'node:type:product:title_label',
    'translation' => 'Nom',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Naam', array(), array('context' => 'type:product:title_label'));
  return $translations;
}
