# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'compass', '~>1.0.3'
gem 'sass', '3.4.13'
gem 'gridle', '2.0.4'
gem 'chunky_png', '1.3.0'
gem 'multi_json', '1.9.3'
gem 'compass-core', '1.0.3'
gem 'compass-import-once', '1.0.5'
gem 'rb-fsevent', '0.9.4'
gem 'ffi', '1.9.8'
gem 'rb-inotify', '0.9.5'
gem 'bundler', '1.9.4'
